const questionbank = [
  {
    id: 1,
    type: "input",
    title: "What do we call you?",
  },
  {
    id: 2,
    type: "input",
    title: "Where can we drop you an email that's not your spam folder?",
  },
  {
    id: 3,
    type: "input",
    title: "We won't call you during dinner, but when can we reach you?",
  },
  {
    id: 4,
    type: "input",
    title:
      "What's the name of your brand? (Hint: We're here to make it famous!)",
  },
  {
    id: 5,
    type: "select",
    title:
      "In which industry do you want to rule the world? (Tell us, we're all ears.)",
    options: [
      "Clothing",
      "Accessories",
      "Footwear",
      "Handbags and Luggage",
      "Watches",
      "Beauty and Personal Care",
      "Intimate Apparel",
      "Kid's Clothing and Accessories",
      "Home Goods",
      "Others",
    ],
  },
  {
    id: 6,
    type: "select",
    title:
      "What kind of business sorcery do you specialize in? (Give us the magical details!))",
    options: ["B2B", "B2C or D2C", "Marketplace or Dropshipping", "Others"],
  },
  {
    id: 7,
    type: "select",
    title: "In which corner of the world does your business HQ reside?",
    options: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Brazil",
      "Canada",
      "China",
      "Colombia",
      "Egypt",
      "France",
      "Germany",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Italy",
      "Japan",
      "Kenya",
      "Malaysia",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Nigeria",
      "Pakistan",
      "Peru",
      "Philippines",
      "Poland",
      "Russia",
      "Saudi Arabia",
      "Singapore",
      "South Africa",
      "South Korea",
      "Spain",
      "Sweden",
      "Switzerland",
      "Taiwan",
      "Thailand",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "United States",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    id: 8,
    type: "select",
    title: "How can we assist you in mastering the digital landscape?",
    options: [
      "E-Commerce Website Development",
      "360° Digital Marketing Services",
      "E-Commerce Website Development and 360° Digital Marketing Services",
      "Others",
    ],
  },
  {
    id: 9,
    type: "select",
    title: "How much gold does your website haul in a month on average?",
    options: [
      "Less than ₹50,000",
      "₹50,000 - ₹1L",
      "₹1L - ₹3L",
      "₹3L - ₹5L",
      "₹5L - ₹10L",
      "₹10L - ₹20L",
      "₹20L - ₹50L",
      "More than ₹50L",
    ],
  },
  {
    id: 10,
    type: "select",
    title:
      "How much of your treasure are you willing to spend on this exciting project? (What's your budget for this?)",
    options: [
      "Less than ₹50K",
      "₹50K - ₹1L",
      "₹1L - ₹5L",
      "₹5L - ₹10L",
      "₹10L - ₹20L",
      "₹20L - ₹25L",
      "More than ₹25L",
    ],
  },
  {
    id: 11,
    type: "select",
    title: "How much is your estimated spend on monthly marketing adventures?",
    options: [
      "Less than ₹50K",
      "₹50K - ₹1L",
      "₹1L - ₹1.5L",
      "₹1.5L - ₹2L",
      "₹2L - ₹4L",
      "₹4L - ₹8L",
      "₹8L - ₹15L",
      "More than ₹15L",
    ],
  },
  {
    id: 12,
    type: "input",
    title:
      "Drop us the secret map to your current website's hideout. (URL, please!)",
  },
  {
    id: 13,
    type: "select",
    title: "How much gold does your website haul in a month on average?",
    options: [
      "Less than $1000",
      "$1K - $2K",
      "$2K - $4K",
      "$4K - $8K",
      "$8K - $15K",
      "$15K - $45K",
      "$45K - $65K",
      "More than $65K",
    ],
  },
  {
    id: 14,
    type: "select",
    title:
      "How much of your treasure are you willing to spend on this exciting project? (What's your budget for this?)",
    options: [
      "Less than $600",
      "$600 - $1200",
      "$1200 - $6K",
      "$6K - $12K",
      "$12K - $24K",
      "$24K - $30K",
      "More than $30K",
    ],
  },
  {
    id: 15,
    type: "select",
    title: "How much is your estimated spend on monthly marketing adventures?",
    options: [
      "Less than $600",
      "$600-$1,200",
      "$1,200-$1,800",
      "$1,800-$2,400",
      "$2,400-$4,800",
      "$4,800-$9,600",
      "$9,600-$18,000",
      "More than $18,000",
    ],
  },
  {
    id: 16,
    type: "select",
    title:
      "Are you looking for a dazzling new website or a thrilling website makeover?",
    options: ["New Website", "Revamp"],
  },
  {
    id: 17,
    type: "input",
    title:
      "If it's a makeover, share the coordinates to your current web kingdom (URL, please!)",
  },
  {
    id: 18,
    type: "select",
    title:
      "How much of your treasure are you willing to spend on this exciting project? (What's your budget for this?)",
    options: [
      "Less than ₹25K",
      "₹25K - ₹50K",
      "₹50K - ₹1L",
      "₹1L - ₹1.5L",
      "₹1.5L - ₹2L",
      "More than ₹2L",
    ],
  },
  {
    id: 19,
    type: "select",
    title:
      "How would you like to send smoke signals? (Preferred communication language?)",
    options: ["English", "Hindi", "Others"],
  },
  {
    id: 20,
    type: "input",
    title:
      "Got any secret messages, treasure maps, or messages in a bottle for us? (Share them here!)",
  },
];

// For test purpose.
// const questionbank = [
//   {
//     id: 1,
//     title: "What do we call you?",
//   },
//   {
//     id: 2,
//     title: "Where can we drop you an email that's not your spam folder?",
//   },
//   {
//     id: 3,
//     title: "We won't call you during dinner, but when can we reach you?",
//   },
// ];

export default questionbank;
